### ISSUE TITLE
Open Selected Picture fails with TypeError

### ISSUE THREAD

**Issue by Head-on-a-Stick** [nwg-piotr/azote#38]
Steps to reproduce: select picture then press the "Open Selected Picture" button.

Expected result: see list of available openers.

Actual result: no list appears.

This error is returned:
```
Traceback (most recent call last):
  File "main.py", line 669, in on_open_button
    openers = common.associations[common.selected_wallpaper.source_path.split('.')[-1]]
TypeError: 'NoneType' object is not subscriptable
```
Happens in both X.org (dwm) & Wayland (sway) under Debian buster.

**Comment by nwg-piotr** [comment]
This may happen if the `/usr/share/applications/mimeinfo.cache` file is missing from the system. 

To regenerate the file:
```
$ sudo update-desktop-database
```

In v1.3.0 some fallback has been added: if `/usr/share/applications/mimeinfo.cache` file not found, the "Open selected picture" button will open it with feh, instead of displaying the menu.
